import { useEffect, useMemo, useState } from "react";
import { IdCardPreview } from "../components/IdCardPreview";

const CLASS_LIST = [
  "Nursery",
  "LKG",
  "UKG",
  "Class 1",
  "Class 2",
  "Class 3",
  "Class 4",
  "Class 5",
  "Class 6",
  "Class 7",
  "Class 8",
  "Class 9",
  "Class 10",
  "Class 11",
  "Class 12",
];

function createEmptyClassMap() {
  return CLASS_LIST.reduce((acc, className) => {
    acc[className] = [];
    return acc;
  }, {});
}

function createEmptyForm(className) {
  return {
    className,
    studentName: "",
    rollNo: "",
    idCardNo: "",
    fees: "",
  };
}

function normalizeClassName(value) {
  const raw = String(value || "").trim().toLowerCase();
  if (!raw) return "";
  if (raw === "nursery") return "Nursery";
  if (raw === "lkg") return "LKG";
  if (raw === "ukg") return "UKG";

  const match = raw.match(/(?:class\s*)?(\d{1,2})(?:st|nd|rd|th)?/);
  if (!match) return "";
  const number = Number.parseInt(match[1], 10);
  if (number >= 1 && number <= 12) {
    return `Class ${number}`;
  }
  return "";
}

function makeLocalStudentRecord(payload) {
  return {
    localId:
      typeof crypto !== "undefined" && crypto.randomUUID
        ? crypto.randomUUID()
        : `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    studentName: payload.studentName.trim(),
    rollNo: payload.rollNo.trim(),
    idCardNo: payload.idCardNo.trim(),
    fees: payload.fees.trim(),
  };
}

export function StudentsSection({
  students = [],
  files = [],
  studentForm = {
    schoolName: "",
    className: "",
    studentId: "",
    name: "",
    rollNo: "",
    parentName: "",
    phone: "",
  },
  setStudentForm = () => {},
  studentStatus = "",
  onGenerateStudentId = () => {},
  onSaveStudent = () => {},
  generatedStudentCard = null,
  isEditingStudent = false,
  onEditStudent = () => {},
  onResetStudentForm = () => {},
}) {
  const [selectedClass, setSelectedClass] = useState(CLASS_LIST[0]);
  const [classStudents, setClassStudents] = useState(() => createEmptyClassMap());
  const [form, setForm] = useState(() => createEmptyForm(CLASS_LIST[0]));
  const [editingId, setEditingId] = useState(null);
  const [selectedRowId, setSelectedRowId] = useState(null);
  const [localStatus, setLocalStatus] = useState("");
  const [lastAutoGeneratedKey, setLastAutoGeneratedKey] = useState("");

  useEffect(() => {
    setForm(createEmptyForm(selectedClass));
    setEditingId(null);
    setLocalStatus("");
  }, [selectedClass]);

  useEffect(() => {
    const schoolName = String(studentForm.schoolName || "").trim();
    const className = String(studentForm.className || "").trim();

    if (!schoolName || !className) {
      setLastAutoGeneratedKey("");
      return;
    }

    const key = `${schoolName.toLowerCase()}::${className.toLowerCase()}`;
    if (key === lastAutoGeneratedKey) return;

    const timer = window.setTimeout(() => {
      onGenerateStudentId();
      setLastAutoGeneratedKey(key);
    }, 450);

    return () => window.clearTimeout(timer);
  }, [studentForm.schoolName, studentForm.className, lastAutoGeneratedKey]);

  useEffect(() => {
    if (!students.length) return;

    setClassStudents((current) => {
      const next = Object.fromEntries(
        Object.entries(current).map(([className, list]) => [className, [...list]]),
      );
      let changed = false;

      students.forEach((student) => {
        const className = normalizeClassName(student.className);
        if (!className || !next[className]) return;

        const record = {
          localId: `api-${student.id || student.name}-${student.rollNo}`,
          studentName: String(student.name || "").trim(),
          rollNo: String(student.rollNo || "").trim(),
          idCardNo: String(student.id || "").trim(),
          fees: String(student.fees || "").trim(),
        };

        if (!record.studentName || !record.rollNo) return;

        const alreadyExists = next[className].some(
          (item) =>
            item.studentName.toLowerCase() === record.studentName.toLowerCase() &&
            item.rollNo === record.rollNo,
        );

        if (!alreadyExists) {
          next[className].push(record);
          changed = true;
        }
      });

      return changed ? next : current;
    });
  }, [students]);

  const studentsInSelectedClass = classStudents[selectedClass] || [];

  const selectedTableStudent = studentsInSelectedClass.find((item) => item.localId === selectedRowId) || null;

  const selectedStudentFiles = useMemo(() => {
    if (!selectedTableStudent) return [];

    return files.filter((item) => {
      const sameClass = normalizeClassName(item.className) === selectedClass;
      const sameName =
        String(item.studentName || "").trim().toLowerCase() ===
        selectedTableStudent.studentName.trim().toLowerCase();
      const sameRoll = String(item.rollNo || "").trim() === selectedTableStudent.rollNo;
      return sameClass && sameName && sameRoll;
    });
  }, [files, selectedClass, selectedTableStudent]);

  const admissionCardPreview = useMemo(() => {
    const base = generatedStudentCard || {};
    return {
      id: String(studentForm.studentId || base.id || "Pending ID").trim(),
      schoolName: String(studentForm.schoolName || base.schoolName || "School Name").trim(),
      name: String(studentForm.name || base.name || "Student Name").trim(),
      className: String(studentForm.className || base.className || "Class").trim(),
      rollNo: String(studentForm.rollNo || base.rollNo || "Roll No").trim(),
      parentName: String(studentForm.parentName || base.parentName || "-").trim(),
      phone: String(studentForm.phone || base.phone || "-").trim(),
    };
  }, [generatedStudentCard, studentForm]);

  const handleInputChange = (key, value) => {
    setForm((current) => ({ ...current, [key]: value }));
  };

  const handleAdminFieldChange = (key, value) => {
    setStudentForm((current) => ({ ...current, [key]: value }));
  };

  const resetForm = () => {
    setForm(createEmptyForm(selectedClass));
    setEditingId(null);
  };

  const handleSubmit = (event) => {
    event.preventDefault();

    if (!form.studentName.trim() || !form.rollNo.trim() || !form.idCardNo.trim() || !form.fees.trim()) {
      setLocalStatus("Student name, roll no, ID card no aur fees sab fill karo.");
      return;
    }

    setClassStudents((current) => {
      const list = current[selectedClass] || [];

      const duplicate = list.find(
        (item) =>
          item.localId !== editingId &&
          (item.rollNo === form.rollNo.trim() || item.idCardNo === form.idCardNo.trim()),
      );

      if (duplicate) {
        setLocalStatus("Is class me roll no ya ID card no already exists.");
        return current;
      }

      const nextList = editingId
        ? list.map((item) =>
            item.localId === editingId
              ? {
                  ...item,
                  studentName: form.studentName.trim(),
                  rollNo: form.rollNo.trim(),
                  idCardNo: form.idCardNo.trim(),
                  fees: form.fees.trim(),
                }
              : item,
          )
        : [makeLocalStudentRecord(form), ...list];

      setLocalStatus(editingId ? "Student updated." : "Student added.");
      return { ...current, [selectedClass]: nextList };
    });

    resetForm();
  };

  const handleEdit = (student) => {
    setEditingId(student.localId);
    setSelectedRowId(student.localId);
    setForm({
      className: selectedClass,
      studentName: student.studentName,
      rollNo: student.rollNo,
      idCardNo: student.idCardNo,
      fees: student.fees,
    });
    setLocalStatus("Edit mode active.");
  };

  const handleDelete = (studentId) => {
    setClassStudents((current) => {
      const nextList = (current[selectedClass] || []).filter((item) => item.localId !== studentId);
      return { ...current, [selectedClass]: nextList };
    });

    if (editingId === studentId) {
      resetForm();
    }
    if (selectedRowId === studentId) {
      setSelectedRowId(null);
    }
    setLocalStatus("Student deleted.");
  };

  return (
    <section className="section-shell">
      <h2>Student Section</h2>
      <p className="muted">Nursery se Class 12 tak class-wise student list, form, edit aur delete.</p>

      <div className="split-grid">
        <article className="panel">
          <h3>Admin Student Admission Form</h3>
          <p className="muted">
            {isEditingStudent
              ? "Edit mode active: student update hoga. Save ke baad form clear ho jayega."
              : "Admin form fill kare aur student add hote hi ID card generate hoga."}
          </p>
          <div className="inline-row inline-row-right">
            <button type="button" onClick={onResetStudentForm}>
              New Form
            </button>
          </div>
          <form className="form-grid" onSubmit={onSaveStudent}>
            <input
              placeholder="School Name"
              value={studentForm.schoolName}
              onChange={(event) => handleAdminFieldChange("schoolName", event.target.value)}
              required
            />
            <select
              value={studentForm.className}
              onChange={(event) => handleAdminFieldChange("className", event.target.value)}
              required
            >
              <option value="">Select Class</option>
              {CLASS_LIST.map((className) => (
                <option key={`admin-${className}`} value={className}>
                  {className}
                </option>
              ))}
            </select>
            <div className="inline-row">
              <input
                placeholder="Student ID"
                value={studentForm.studentId}
                onChange={(event) => handleAdminFieldChange("studentId", event.target.value)}
              />
              <button type="button" onClick={onGenerateStudentId}>
                Generate ID
              </button>
            </div>
            <input
              placeholder="Student Name"
              value={studentForm.name}
              onChange={(event) => handleAdminFieldChange("name", event.target.value)}
              required
            />
            <input
              placeholder="Roll No"
              value={studentForm.rollNo}
              onChange={(event) => handleAdminFieldChange("rollNo", event.target.value)}
              required
            />
            <input
              placeholder="Parent Name"
              value={studentForm.parentName}
              onChange={(event) => handleAdminFieldChange("parentName", event.target.value)}
            />
            <input
              placeholder="Phone"
              value={studentForm.phone}
              onChange={(event) => handleAdminFieldChange("phone", event.target.value)}
            />
            <button type="submit">{isEditingStudent ? "Update Student" : "Add Student + Generate ID Card"}</button>
          </form>
          <p className="status-text">{studentStatus}</p>
        </article>

        <IdCardPreview
          type="student"
          data={admissionCardPreview}
          emptyText="Student ID card side preview always visible rahega."
        />
      </div>

      <article className="panel">
        <h3>Saved Students (Mongo + Screen)</h3>
        <p className="muted">Yaha saved students dikhte rahenge. Galti ho to Edit button se form me load karo.</p>
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Class</th>
                <th>Roll</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {students.length === 0 && (
                <tr>
                  <td colSpan="5" className="empty-cell">
                    No students saved yet.
                  </td>
                </tr>
              )}
              {students.map((student) => (
                <tr key={`saved-${student.id}`}>
                  <td>{student.id}</td>
                  <td>{student.name}</td>
                  <td>{student.className}</td>
                  <td>{student.rollNo}</td>
                  <td>
                    <div className="table-actions">
                      <button
                        type="button"
                        className="button-secondary"
                        onClick={() => onEditStudent(student)}
                      >
                        Edit
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </article>

      <div className="student-class-layout">
        <article className="panel">
          <h3>Class Menu</h3>
          <p className="muted">Class select karke uske students manage karo.</p>
          <div className="class-list-box">
            {CLASS_LIST.map((className) => (
              <button
                type="button"
                key={className}
                className={`class-list-item ${selectedClass === className ? "active" : ""}`}
                onClick={() => setSelectedClass(className)}
              >
                <span>{className}</span>
                <small>{classStudents[className]?.length || 0} students</small>
              </button>
            ))}
          </div>
        </article>

        <article className="panel">
          <h3>{selectedClass} Student Form</h3>
          <form className="form-grid" onSubmit={handleSubmit}>
            <input value={selectedClass} readOnly aria-label="Selected Class" />
            <input
              placeholder="Student Name"
              value={form.studentName}
              onChange={(event) => handleInputChange("studentName", event.target.value)}
              required
            />
            <input
              placeholder="Roll No"
              value={form.rollNo}
              onChange={(event) => handleInputChange("rollNo", event.target.value)}
              required
            />
            <input
              placeholder="ID Card No"
              value={form.idCardNo}
              onChange={(event) => handleInputChange("idCardNo", event.target.value)}
              required
            />
            <input
              placeholder="Fees"
              value={form.fees}
              onChange={(event) => handleInputChange("fees", event.target.value)}
              required
            />
            <div className="inline-row">
              <button type="submit">{editingId ? "Update Student" : "Add Student"}</button>
              <button type="button" className="button-secondary" onClick={resetForm}>
                Reset
              </button>
            </div>
          </form>
          <p className="status-text">{localStatus}</p>
        </article>

        <article className="panel">
          <h3>{selectedClass} Student List</h3>
          <p className="muted">Student select karke edit karo ya delete karo.</p>
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Roll No</th>
                  <th>ID Card No</th>
                  <th>Fees</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {studentsInSelectedClass.length === 0 && (
                  <tr>
                    <td colSpan="5" className="empty-cell">
                      No students added in {selectedClass}.
                    </td>
                  </tr>
                )}
                {studentsInSelectedClass.map((student) => (
                  <tr
                    key={student.localId}
                    className={selectedRowId === student.localId ? "selected-table-row" : ""}
                    onClick={() => setSelectedRowId(student.localId)}
                  >
                    <td>{student.studentName}</td>
                    <td>{student.rollNo}</td>
                    <td>{student.idCardNo}</td>
                    <td>{student.fees}</td>
                    <td>
                      <div className="table-actions">
                        <button
                          type="button"
                          className="button-secondary"
                          onClick={(event) => {
                            event.stopPropagation();
                            handleEdit(student);
                          }}
                        >
                          Edit
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </article>
      </div>

      <article className="panel">
        <h3>Selected Student Files</h3>
        {!selectedTableStudent && (
          <p className="empty-text">Student row select karo to files dikhengi (agar uploaded hain).</p>
        )}
        {selectedTableStudent && (
          <>
            <p className="muted">
              {selectedTableStudent.studentName} | {selectedClass} | Roll {selectedTableStudent.rollNo}
            </p>
            {selectedStudentFiles.length === 0 && <p className="empty-text">Is student ke files nahi mile.</p>}
            {selectedStudentFiles.length > 0 && (
              <div className="table-wrap">
                <table>
                  <thead>
                    <tr>
                      <th>Type</th>
                      <th>File</th>
                      <th>Submitted</th>
                    </tr>
                  </thead>
                  <tbody>
                    {selectedStudentFiles.map((item) => (
                      <tr key={item.id}>
                        <td>{item.documentType}</td>
                        <td>
                          <a href={item.fileUrl} target="_blank" rel="noreferrer">
                            Open File
                          </a>
                        </td>
                        <td>{new Date(item.submittedAt).toLocaleString()}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </>
        )}
      </article>
    </section>
  );
}
